### ISSUE TITLE
Completare il server

### ISSUE THREAD

**Issue by luca2040** [Luca2040/RiassuntoCircolari#1]
La pagina deve contenere:

- Dropdown per selezionare il destinatario (per esempio studenti)
- Dopo aver selezionato il destinatario si può scegliere la classe e sezione con un altro dropdown
- Elenco delle circolari che soddisfano i requisiti indicati prima e quando ne viene selezionata una compare il riassunto (nel DB i riassunti sono salvati usando Markdown)

**Comment by MatteoGheza** [comment]
Per "destinatario" si intende a chi sono rivolte delle circolari?
In questo caso, avviene un filtraggio delle circolari da restituire?
Ci sono dei cambi nella personalità del chatbot tra le diverse tipologie di destinatario?

**Comment by luca2040** [comment]
il destinatario è la persona che deve leggere la circolare, quando le circolari vengono caricate nel db l'llm ricava il destinatario automaticamente.
Per la personalità quella è sempre la stessa, alla fine si era deciso di salvare nel db le circolari già riassunte e poi semplicemente visualizzare il risultato nella pagina del server.
